version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: motor-adaptativo-postgres
    restart: always
    environment:
      POSTGRES_USER: uabc_admin
      POSTGRES_PASSWORD: uabc_password
      POSTGRES_DB: motor_adaptativo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
